{
 "title": "OBS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    { "expr": "bitrate{}" }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "cpu_usage_percent{}" }
   ]
  },
  {
   "title": "Total Frames Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {},
    { "expr": "dropped_frames{}" }
   ]
  },
  {
   "title": "Frames Dropped %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "frames_dropped_percent{}" }
   ]
  }
 ]
}